### ISSUE TITLE
Apache Server

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#100]
works well. What's this? script src="//hogg-blake.co.uk:3000/hit/ni1kbk"
The program is good! Languages support is missing. I could help..
German is a beautiful language.
Best regards R.U.
closed...

**Comment by gushogg-blake** [comment]
Great - glad you got it working.  That's a hit counter I made - it was using statcounter.com before but that stopped working for some reason.

I agree!  Language support shouldn't be too hard to add - I'll create a new issue on here and start working on it.  If you could make a list of English to German translations that would be excellent.  This format would be best:

```
English phrase=German phrase
Other words=German phrase #optional comment to clarify where the text is on the website
```

etc
