### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by gushogg-blake** [jsonchess/lightsquare#101]
- Convert text to use l10n/i18n library
- Add a language selector at the top
- Remember the language selection with a cookie

**Comment by antiproton** [comment]
# German translation
Home = Home
New game = Neue Partie
Current games = Laufende Partien
Tools = Tools
Restore game = Partie speichern
Games = Partien
Start game = Partie starten
Cancel = Abbrechen
Initaltime = Zeit
Increment = Aufschlag
Min. opponent rating = Gegner min. Elo
Max. opponent rating = Gegner max Elo
To find an opponent click Start game, or accept a seek from the graph. = Man kann selbst ein Spiel starten, oder man klickt auf eine Forderung. 
Premove = vorweggenommener Antwortzug
Allways queen = Immer in Dame umwandeln
Flip board = Brett drehen
Rematch = Rematch
Send = Senden
Resign = Aufgeben
Offer draw = Remis anbieten

**Comment by gushogg-blake** [comment]
Excellent, I'll start work on this tomorrow

**Comment by gushogg-blake** [comment]
Some text has been converted - still working on the language selector.

To see the translations so far you can add ?locale=de to the URL.

**Comment by antiproton** [comment]
Absolutely horny!
Connecting to the server... =  Vebindung zum Server wird aufgebaut.....
Connection problem – if you see this after reloading, the server may have gone down. Otherwise, check your internet connection = Verbindung kann nicht aufgebaut werden. Benachrichtigen Sie den Administrator!

Best Regards R. U.
http://netreal.de/bot-chess/index.php
http://netreal.de/online-chess/index.php

**Comment by gushogg-blake** [comment]
Thanks, have added those.

**Comment by antiproton** [comment]
I have 1,000 ideas.....
Best Regards

**Comment by gushogg-blake** [comment]
Keep them coming!  There are too many features to choose from, so it's good to get feedback from users and see what's most important

**Comment by antiproton** [comment]
Some things. Then you can ask for money ..
Best Regards R. U.

**Comment by antiproton** [comment]
The following languages can be translated well!  Without Google!
Polish
Turkish
Vietnamese

Give me a file: English - other language
Best regards R. U.
