### ISSUE TITLE
Extension of the menus

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#109]
Is the expansion of menus possible? With links to html/PHP files. Using a configuration file? Which file should you use?
Best Regards R. U.
![menu](https://cloud.githubusercontent.com/assets/6153753/5872509/9bb8aa86-a2ec-11e4-86cd-43648d621a43.jpg)

**Comment by gushogg-blake** [comment]
Those links are just plain HTML.  On line 34 of /js/Lightsquare/lightsquare.html there is a .control_panel div which has the Log in and Create account links in it -- you can add more links in there.

I would also recommend renaming the div to .top_nav or something as .control_panel doesn't sound right for a general link area.
