### ISSUE TITLE
move with sound?

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#113]
it is possible move with sound? like this: http://netreal.de/bot-chess
Best Regards R.U.

**Comment by gushogg-blake** [comment]
Yes, I'll borrow the .wav from your site if you don't mind?

**Comment by antiproton** [comment]
Absolutely brilliant.... R. U.

**Comment by antiproton** [comment]
I have installed the latest version, but I can not hear sound? Why?
http://217.160.184.14
