### ISSUE TITLE
Client Bug

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#115]
Login: test2 no guest!!!
1. I click on new game
2. I click on new game
3. I click on cancel and so on....and see:

![main](https://cloud.githubusercontent.com/assets/6153753/5924407/cadf9262-a65b-11e4-82b1-14aafc53abc6.jpg)

**Comment by gushogg-blake** [comment]
Thanks - I think this may be a bug in Ractive.  If you look in the template for the SeekForm there is a conditional that logically prevents both the Start game and Cancel buttons being shown.  I'll check this out and file a bug with Ractive if it turns out to be that.

**Comment by gushogg-blake** [comment]
I have narrowed it down to the i18n method - apparently ractive doesn't allow you to have an expression (`__("Start game")`) as a form value because of its two-way binding, and I think this is what's causing the issue.

**Comment by antiproton** [comment]
Can the problem be solved??
Best Regards R.U.

**Comment by gushogg-blake** [comment]
If you reinstall bower dependencies now it should be resolved.

```
rm -rf bower_components/ractive bower_components/ractive-i18n
bower install
```
