### ISSUE TITLE
New Version I

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#121]
the new version of Prgrammes not work for me.
See: http://realschach.de/
Click on stockfish

ParseError: Unexpected closing tag (<source> is a void element - it cannot contain children) at line 30 character 68:
    <source src="{{getAbsolutePath("./move.wav")}}" type="audio/wav"></source>                                                                   ^----
TypeError: this._history is undefined
...;this._game.Move.addHandler(function(e){this._history.move(e),this._template.set...	
main.js...4738329 (Zeile 46, Spalte 307457)
Ractive.js: Two-way binding does not work with expressions (`__("Rematch")` on <input>) <div class="game">
main.js...4738329 (Zeile 46)
Ractive.js: Two-way binding does not work with expressions (`__("Decline")` on <input>) <div class="game">
main.js...4738329 (Zeile 46)
SyntaxError: [sprintf] unexpected placeholder
...((r=t.placeholder.exec(n))===null)throw new SyntaxError("[sprintf] unexpected pl...	
main.js...4738329 (Zeile 46, Spalte 63131)
TypeError: this._board is undefined
	
...e},m.prototype._clearPremove=function(){this._board.setBoardArray(this._game.pos...

**Comment by gushogg-blake** [comment]
When did you pull the code?  Did you run npm install and bower install again?  I fixed some issues caused by the latest versions of some libraries, so it should be working now

**Comment by antiproton** [comment]
Yes, but I have error messages.
sudo npm install -g bower
bower install --allow-root
bower invalid-meta  lightsquare is missing "main" entry in bower.json
bower invalid-meta  lightsquare is missing "ignore" entry in bower.json
bower resolved      /var/www/lightsquare/js
bower checkout      require-text#master
bower checkout      require-css#master
bower checkout      require-domReady#master
bower checkout      ractive-i18n#master
bower invalid-meta  Array.prototype is missing "main" entry in bower.json
bower invalid-meta  Array.prototype is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/Array.prototype.git#4bfb3adf4e
bower invalid-meta  json-local-storage is missing "main" entry in bower.json
bower invalid-meta  json-local-storage is missing "ignore" entry in bower.json
bower invalid-meta  js is missing "main" entry in bower.json
bower invalid-meta  js is missing "ignore" entry in bower.json
bower invalid-meta  routing is missing "main" entry in bower.json
bower invalid-meta  routing is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/json-local-storage.git#010e5864c0
bower resolved      git://github.com/gushogg-blake/js.git#36faa9ed2b
bower resolved      git://github.com/gushogg-blake/routing.git#8cde2f40cb
bower invalid-meta  websocket-client is missing "main" entry in bower.json
bower invalid-meta  websocket-client is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/websocket-client.git#9303f8eb80
bower invalid-meta  tokeniser is missing "main" entry in bower.json
bower invalid-meta  tokeniser is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/tokeniser.git#7aa0cafc9d
bower invalid-meta  dom is missing "main" entry in bower.json
bower invalid-meta  dom is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/dom.git#f945f003c1
bower invalid-meta  jsonchess is missing "main" entry in bower.json
bower invalid-meta  jsonchess is missing "ignore" entry in bower.json
bower resolved      git://github.com/jsonchess/jsonchess.git#0b1960860b
bower invalid-meta  chess is missing "main" entry in bower.json
bower invalid-meta  chess is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/chess.git#af2d17e446
bower invalid-meta  text is missing "ignore" entry in bower.json
bower resolved      git://github.com/requirejs/text.git#26643989f5
bower invalid-meta  require-domReady is missing "main" entry in bower.json
bower invalid-meta  require-domReady is missing "ignore" entry in bower.json
bower resolved      git://github.com/requirejs/domReady.git#449478e133
bower invalid-meta  ractive-i18n is missing "main" entry in bower.json
bower invalid-meta  ractive-i18n is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/ractive-i18n.git#969a09b3bb
bower not-cached    git://github.com/gushogg-blake/i18n.git#master
bower resolve       git://github.com/gushogg-blake/i18n.git#master
bower cached        git://github.com/rse/sprintfjs.git#1.1.9
bower validate      1.1.9 against git://github.com/rse/sprintfjs.git#*
bower resolved      git://github.com/guybedford/require-css.git#3b1d868582
bower checkout      i18n#master
bower invalid-meta  i18n is missing "main" entry in bower.json
bower invalid-meta  i18n is missing "ignore" entry in bower.json
bower resolved      git://github.com/gushogg-blake/i18n.git#641ad3c1ea
bower cached        git://github.com/alexei/sprintf.js.git#1.0.2
bower validate      1.0.2 against git://github.com/alexei/sprintf.js.git#*
bower invalid-meta  require is missing "main" entry in bower.json
bower invalid-meta  require is missing "ignore" entry in bower.json
bower resolved      git://github.com/jrburke/requirejs.git#4812bb3418

**Comment by antiproton** [comment]
The latest version is not working. Best regards!
