### ISSUE TITLE
Stockfish

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#95]
I have installed your program. It works very well. Stockfish is not working for me 
I installed code with 
sudo apt-get install stockfish. 
Then
root @ s1811580: ~ / light squared # forever start main.js --bots 1
Warning: --minUptime not set. Defaulting to: 1000ms
Warning: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info: Forever processing file: main.js
root @ s1811580: ~ / light squared #
I can not see stockfish. Best regards!

**Comment by gushogg-blake** [comment]
Looks like you just need more bots - the one created is probably just waiting for a challenge

**Comment by gushogg-blake** [comment]
Stockfish takes up about 38MB of memory and the bots keep an instance running all the time, so in theory you can run however many MB of free ram you have divided by 38.

They could be modified to only start Stockfish when they need to make a move, and somehow negotiate with each other to prevent too many concurrent instances, which would make them more memory-efficient but would add some complexity.
