### ISSUE TITLE
pawn conversion

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#97]
If you do not Always queen ticking. Then the pawn conversion does not work. A blank message you see. Sorry for my english. :-)

**Comment by gushogg-blake** [comment]
Strange - can you post a screenshot?  It should bring up a small box with buttons for each piece.

**Comment by antiproton** [comment]
I see a small box without figures. The position was created during a game. I clicked into the empty box and got a ROOK

**Comment by gushogg-blake** [comment]
OK cool, sounds like it was a temporary problem loading the piece images in.
