### ISSUE TITLE
 Stability of the server - SimpleHTTPServer

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#98]
I think the stockfish in the stability of the server problems makes. I watch it.

**Comment by gushogg-blake** [comment]
Do you see the app, with the yellow "server disconnected" bar at the top, or is it just hanging/blank page?  This will determine whether it's to do with the Node server (lightsquared) or something else.

**Comment by antiproton** [comment]
hanging/blank page!

**Comment by gushogg-blake** [comment]
It seems like it's to do with SimpleHTTPServer then - I don't think it's recommended for long-running web servers.  Nginx, Apache, Lighttpd, etc would be better.

**Comment by antiproton** [comment]
Then I did not understand something. How to use Apache exactly?

**Comment by gushogg-blake** [comment]
Everything will be in the Apache documentation, but basically you would install Apache ($sudo apt-get install apache2 I think) and then add the code in the README to the end of the Apache config file, which is usually /etc/apache2/conf/apache2.conf or httpd.conf.

If you're only running Lightsquare under Apache you can take everything out of the <VirtualHost> tag.  VirtualHosts are a way of serving different websites based on the URL.
